name = "spectral_run"
version = "1.0.0"
target = "javascript"











[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
paint = ">= 1.0.1 and < 2.0.0"
tiramisu = ">= 6.1.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"







